In [2]:
import streamlit as st
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, StandardScaler
from sklearn.model_selection import train_test_split
import pickle   

data=pd.read_csv("Churn_Modelling.csv")
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [3]:
# Preprocess data
data
data= data.drop(["RowNumber", "CustomerId", "Surname"], axis=1)

In [ ]:
#lable Encoding for the Gender(Fit- Find unique values from gender sort them into alphabetical order)
#Transform - Convert the unique text values into numerical valus are zeros and 1 s
label_encoder=LabelEncoder()
data['Gender']=label_encoder.fit_transform(data['Gender'])
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,1,39,5,0.00,2,1,0,96270.64,0
9996,516,France,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,0,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,0,28,4,130142.79,1,1,0,38190.78,0

In [5]:
##Onehot encoding for the geography
import pickle
onehot_encoder = OneHotEncoder(sparse_output=True)
geo_encoded = onehot_encoder.fit_transform(data[["Geography"]]).toarray()
column_names = onehot_encoder.get_feature_names_out(["Geography"])
geo_encoded_df = pd.DataFrame(geo_encoded, columns=column_names)
data1 = data.drop("Geography", axis=1)
##Combine data
input_data = pd.concat([data1, geo_encoded_df], axis=1)

##Split Data into independent and dependent features
X = input_data.drop("EstimatedSalary", axis=1)
y = input_data["EstimatedSalary"]

##Split data in training and testing sets

X_train, X_test, y_train, y_test = train_test_split(
    X, y, random_state=42, test_size=0.2
)
##Scale this fearures
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [6]:
##Convert Pickle files
with open("label_encoder_gender.pkl", "wb") as file:
    pickle.dump(label_encoder, file)
with open("onehot_encoder_geo.pkl", "wb") as file:
    pickle.dump(onehot_encoder, file)
with open("scaler.pkl", "wb") as file:
   pickle.dump(scaler, file)

##Train the ANN Regression Problem statement

In [7]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [8]:
##Build a Model

model = Sequential(
    [
        Dense(64, activation="relu", input_shape=(X_train.shape[1],)),
        Dense(32, activation="relu"),
        Dense(1),
    ]
)
##Complie the model
model.compile(optimizer="adam", loss="mean_absolute_error", metrics=["mae"])
model.summary()

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

d:\GenAI2026\.venv\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [9]:
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
from datetime import datetime

##Setup Tensorboard
log_dir = "regression_logs/fit/" + datetime.now().strftime("%Y%m%d-%H%M%S")

tensor_board_callback = TensorBoard(log_dir=log_dir, histogram_freq=1)
##Setup callbacks
early_stopping_callback = EarlyStopping(
    monitor="val_loss", patience=10, restore_best_weights=True
)
##Train the model
history = model.fit(
    X_train,
    y_train,
    validation_data=(X_test, y_test),
    epochs=100,
    callbacks=[tensor_board_callback, early_stopping_callback],
)
#Load Tensorboard
%load_ext tensorboard
%tensorboard --logdir=log_dir
%reload_ext tensorboard

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 100376.1172 - mae: 100376.1172 - val_loss: 98514.7422 - val_mae: 98514.7422
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 99636.7422 - mae: 99636.7422 - val_loss: 97023.8984 - val_mae: 97023.8984
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 97057.8906 - mae: 97057.8906 - val_loss: 93231.1875 - val_mae: 93231.1875
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 91984.9375 - mae: 91984.9375 - val_loss: 86898.0547 - val_mae: 86898.0547
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 84549.7734 - mae: 84549.7734 - val_loss: 78660.9453 - val_mae: 78660.9453
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 75669.9844 - mae: 75669.9844 - val_loss: 69949.3203 - val_mae: 69949.3203
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 66971.7969 - mae: 66971.7969 - val_loss: 62238.1602 - val_mae: 62238.1602
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 59921.2812 - mae: 59921.2812 - val_loss: 56687.6211 - val_mae: 56687.6211
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 55184.9922 - mae: 55184.9922 - val_loss: 53312.0430 - val_mae: 53312.0430
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 52455.2656 - mae: 52455.2656 - val_loss: 51603.6680 - val_mae: 51603.6680
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 51111.7852 - mae: 51111.7852 - val_loss: 50980.7266 - val_mae: 50980.7266
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50554.3008 - mae: 50554.3008 - val_loss: 50768.6406 - val_mae: 50768.6406
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50318.1680 - mae: 50318.1680 - val_loss: 50677.8867 - val_mae: 50677.8867
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50206.9297 - mae: 50206.9297 - val_loss: 50618.7070 - val_mae: 50618.7070
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50134.8125 - mae: 50134.8125 - val_loss: 50571.2227 - val_mae: 50571.2227
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50081.2656 - mae: 50081.2656 - val_loss: 50524.7539 - val_mae: 50524.7539
Epoch 17/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50038.6367 - mae: 50038.6367 - val_loss: 50487.0156 - val_mae: 50487.0156
Epoch 18/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50001.7227 - mae: 50001.7227 - val_loss: 50461.9648 - val_mae: 50461.9648
Epoch 19/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49965.2422 - mae: 49965.2422 - val_loss: 50422.7266 - val_mae: 50422.7266
Epoch 20/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49933.1797 - mae: 49933.1797 - val_loss: 50407.7305 - val_mae: 50407.7305
Epoch 21/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49905.4922 - mae: 49905.4922 - val_loss: 50387.0391 - val_mae: 50387.0391
Epoch 22/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49875.1406 - mae: 49875.1406 - val_loss: 50368.8594 - val_mae: 50368.8594
Epoch 23/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49852.5898 - mae: 49852.5898 - val_loss: 50356.5547 - val_mae: 50356.5547
Epoch 24/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49825.4922 - mae: 49825.4922 - val_loss: 50336.2383 - val_mae: 50336.2383
Epoch 25/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49805.9102 - mae: 49805.9102 - val_loss: 50326.1680 - val_mae: 50326.1680
Epoch 26/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49778.7969 - mae: 49778.7969 - val_loss: 50318.8906 - val_mae: 50318.8906
Epoch 27/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49763.3867 - mae: 49763.3867 - val_loss: 50311.2383 - val_mae: 50311.2383
Epoch 28/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49742.5508 - mae: 49742.5508 - val_loss: 50296.9023 - val_mae: 50296.9023
Epoch 29/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49723.4453 - mae: 49723.4453 - val_loss: 50285.2969 - val_mae: 50285.2969
Epoch 30/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49710.9805 - mae: 49710.9805 - val_loss: 50284.0273 - val_mae: 50284.0273
Epoch 31/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49698.0156 - mae: 49698.0156 - val_loss: 50275.5469 - val_mae: 50275.5469
Epoch 32/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49681.1914 - mae: 49681.1914 - val_loss: 50275.7578 - val_mae: 50275.7578
Epoch 33/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49667.8047 - mae: 49667.8047 - val_loss: 50268.3828 - val_mae: 50268.3828
Epoch 34/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49654.1250 - mae: 49654.1250 - val_loss: 50269.8594 - val_mae: 50269.8594
Epoch 35/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49640.7070 - mae: 49640.7070 - val_loss: 50275.1328 - val_mae: 50275.1328
Epoch 36/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49630.7188 - mae: 49630.7188 - val_loss: 50265.4297 - val_mae: 50265.4297
Epoch 37/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49617.3711 - mae: 49617.3711 - val_loss: 50262.0273 - val_mae: 50262.0273
Epoch 38/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49606.3164 - mae: 49606.3164 - val_loss: 50265.6914 - val_mae: 50265.6914
Epoch 39/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49596.1484 - mae: 49596.1484 - val_loss: 50268.3516 - val_mae: 50268.3516
Epoch 40/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49586.7812 - mae: 49586.7812 - val_loss: 50263.6680 - val_mae: 50263.6680
Epoch 41/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49575.9766 - mae: 49575.9766 - val_loss: 50256.0859 - val_mae: 50256.0859
Epoch 42/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49567.8359 - mae: 49567.8359 - val_loss: 50270.0508 - val_mae: 50270.0508
Epoch 43/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49558.7578 - mae: 49558.7578 - val_loss: 50261.5039 - val_mae: 50261.5039
Epoch 44/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49550.0312 - mae: 49550.0312 - val_loss: 50268.3477 - val_mae: 50268.3477
Epoch 45/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49544.2383 - mae: 49544.2383 - val_loss: 50260.2969 - val_mae: 50260.2969
Epoch 46/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49533.8516 - mae: 49533.8516 - val_loss: 50261.8008 - val_mae: 50261.8008
Epoch 47/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49525.7930 - mae: 49525.7930 - val_loss: 50267.6836 - val_mae: 50267.6836
Epoch 48/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49518.2539 - mae: 49518.2539 - val_loss: 50263.9531 - val_mae: 50263.9531
Epoch 49/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49509.3203 - mae: 49509.3203 - val_loss: 50261.1719 - val_mae: 50261.1719
Epoch 50/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49506.3281 - mae: 49506.3281 - val_loss: 50264.7461 - val_mae: 50264.7461
Epoch 51/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49501.4922 - mae: 49501.4922 - val_loss: 50273.7422 - val_mae: 50273.7422

Reusing TensorBoard on port 6008 (pid 21800), started 0:02:37 ago. (Use '!kill 21800' to kill it.)

In [9]:
##Evaluate the loss for test data

test_loss, test_mae=model.evaluate(X_test, y_test)
print(f'Test MAE is : {test_mae}')

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50302.8086 - mae: 50302.8086
Test MAE is : 50302.80859375

In [10]:
##Save regression model
model.save('regression_model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.